// post
export const CREATE_DATA_REQUEST = "CREATE_DATA_REQUEST";
export const CREATE_DATA_SUCCESS = "CREATE_DATA_SUCCESS";
export const CREATE_DATA_FAIL = "CREATE_DATA_FAIL";
// get
export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_FAIL = "GET_DATA_FAIL";
// single
export const SINGLE_DATA_REQUEST = "SINGLE_DATA_REQUEST";
export const SINGLE_DATA_SUCCESS = "SINGLE_DATA_SUCCESS";
export const SINGLE_DATA_FAIL = "SINGLE_DATA_FAIL";
// update
export const UPDATE_DATA_REQUEST = "UPDATE_DATA_REQUEST";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
export const UPDATE_DATA_FAIL = "UPDATE_DATA_FAIL";
// delete
export const DELETE_DATA_REQUEST = "DELETE_DATA_REQUEST";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const DELETE_DATA_FAIL = "DELETE_DATA_FAIL";